server.port=8084

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/notification_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=${JWT_SECRET:}

spring.mail.host=${SPRING_MAIL_HOST:smtp.gmail.com}
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.username=${EMAIL_USERNAME:}
spring.mail.password=${EMAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

notifylk.user_id=${NOTIFYLK_USER_ID:}
notifylk.api_key=${NOTIFYLK_API_KEY:}
notifylk.sender_id=${NOTIFYLK_SENDER_ID:NotifyDEMO}
