apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-config
data:
  init-databases.sql: |
    CREATE DATABASE user_db;
    CREATE DATABASE doctor_db;
    CREATE DATABASE appointment_db;
    CREATE DATABASE notification_db;
    CREATE DATABASE payment_db;
    CREATE DATABASE telemedicine_db;
    CREATE DATABASE symptom_checker_db;
