apiVersion: v1
kind: Secret
metadata:
  name: healthcare-secret
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "12345"
  SPRING_DATASOURCE_PASSWORD: "12345"
  JWT_SECRET: "iNxBALh1gy6pH/GlVs3HdRhujpbNBzQCVqSr3nLIxJE="
  GEMINI_API_KEY: "replace-with-your-api-key"
