apiVersion: apps/v1
kind: Deployment
metadata:
  name: symptom-checker-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: symptom-checker-service
  template:
    metadata:
      labels:
        app: symptom-checker-service
    spec:
      containers:
        - name: symptom-checker-service
          image: symptom-checker-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8087
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-service:5432/symptom_checker_db"
          envFrom:
            - configMapRef:
                name: healthcare-config
            - secretRef:
                name: healthcare-secret
---
apiVersion: v1
kind: Service
metadata:
  name: symptom-checker-service
spec:
  selector:
    app: symptom-checker-service
  ports:
    - port: 8087
      targetPort: 8087
  type: ClusterIP
