server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/user_db
spring.datasource.username=postgres
spring.datasource.password=12345
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

jwt.secret=${JWT_SECRET}

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

google.client.id=97532193168-o1kt921m7a8gpgu3b5uk7db3v3r8eubo.apps.googleusercontent.com
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=never

# SMTP Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=stylerfree29@gmail.com
spring.mail.password=jbdx wqow erez ynij
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
